### ISSUE TITLE
Enhancement idea

### ISSUE THREAD

**Issue by JohnRCrichton** [screenshakes/Dew#1]
Instead of deleting and reposting the message, would it be possible to have the bot edit the message instead? It would make transitions between images cleaner and less jarring.

**Comment by screenshakes** [comment]
For some reason I never received a notification for this so I am only replying now, sorry about that.
This is not possible as Discord does not let you reupload an image when editing a message.

**Comment by JohnRCrichton** [comment]
You know, that's a fair point that I completely overlooked. Thanks for the reply!
